services:
  - type: web
    name: bitespeed-identity-api
    env: node
    plan: free
    buildCommand: npm ci && npm run prisma:generate && npm run build
    startCommand: npm run prisma:migrate:deploy && npm run start
    envVars:
      - key: NODE_VERSION
        value: 22.22.0
      - key: DATABASE_URL
        sync: false
